<?php

namespace Weglot\Helpers;

abstract class WeglotLang
{
    public static function getCodeLangs()
    {
        return array(
            'af',
            'hw',
            'sq',
            'am',
            'ar',
            'hy',
            'az',
            'ba',
            'eu',
            'be',
            'bn',
            'bs',
            'bg',
            'my',
            'ca',
            'ny',
            'zh',
            'tw',
            'co',
            'hr',
            'cs',
            'da',
            'nl',
            'en',
            'eo',
            'et',
            'fj',
            'fi',
            'fr',
            'fl',
            'gl',
            'ka',
            'de',
            'el',
            'gu',
            'ht',
            'ha',
            'he',
            'hi',
            'hu',
            'is',
            'ig',
            'id',
            'ga',
            'it',
            'ja',
            'jv',
            'kn',
            'kk',
            'km',
            'ko',
            'ku',
            'ky',
            'lo',
            'la',
            'lv',
            'lt',
            'lb',
            'mk',
            'mg',
            'ms',
            'ml',
            'mt',
            'mi',
            'mr',
            'mn',
            'ne',
            'no',
            'ps',
            'fa',
            'pl',
            'pt',
            'pa',
            'ro',
            'ru',
            'sm',
            'gd',
            'sr',
            'sn',
            'sd',
            'si',
            'sk',
            'sl',
            'so',
            'st',
            'es',
            'su',
            'sw',
            'sv',
            'tl',
            'ty',
            'tg',
            'ta',
            'tt',
            'te',
            'th',
            'to',
            'tr',
            'uk',
            'ur',
            'uz',
            'vi',
            'cy',
            'fy',
            'xh',
            'yi',
            'yo',
            'zu',
        );
    }

    public static function getStrLangs()
    {
        return array(
            'af' => __('Afrikaans', 'weglot'),
            'sq' => __('Albanian', 'weglot'),
            'am' => __('Amharic', 'weglot'),
            'ar' => __('Arabic', 'weglot'),
            'hy' => __('Armenian', 'weglot'),
            'az' => __('Azerbaijani', 'weglot'),
            'ba' => __('Bashkir', 'weglot'),
            'eu' => __('Basque', 'weglot'),
            'be' => __('Belarusian', 'weglot'),
            'bn' => __('Bengali', 'weglot'),
            'bs' => __('Bosnian', 'weglot'),
            'bg' => __('Bulgarian', 'weglot'),
            'my' => __('Burmese', 'weglot'),
            'ca' => __('Catalan', 'weglot'),
            'ny' => __('Chichewa', 'weglot'),
            'zh' => __('Simplified Chinese', 'weglot'),
            'tw' => __('Traditional Chinese', 'weglot'),
            'co' => __('Corsican', 'weglot'),
            'hr' => __('Croatian', 'weglot'),
            'cs' => __('Czech', 'weglot'),
            'da' => __('Danish', 'weglot'),
            'nl' => __('Dutch', 'weglot'),
            'en' => __('English', 'weglot'),
            'eo' => __('Esperanto', 'weglot'),
            'et' => __('Estonian', 'weglot'),
            'fj' => __('Fijian', 'weglot'),
            'fi' => __('Finnish', 'weglot'),
            'fl' => __('Filipino', 'weglot'),
            'fr' => __('French', 'weglot'),
            'gl' => __('Galician', 'weglot'),
            'ka' => __('Georgian', 'weglot'),
            'de' => __('German', 'weglot'),
            'el' => __('Greek', 'weglot'),
            'gu' => __('Gujarati', 'weglot'),
            'ht' => __('Haitian', 'weglot'),
            'ha' => __('Hausa', 'weglot'),
            'hw' => __('Hawaiann', 'weglot'),
            'he' => __('Hebrew', 'weglot'),
            'hi' => __('Hindi', 'weglot'),
            'hu' => __('Hungarian', 'weglot'),
            'is' => __('Icelandic', 'weglot'),
            'ig' => __('Igbo', 'weglot'),
            'id' => __('Indonesian', 'weglot'),
            'ga' => __('Irish', 'weglot'),
            'it' => __('Italian', 'weglot'),
            'ja' => __('Japanese', 'weglot'),
            'jv' => __('Javanese', 'weglot'),
            'kn' => __('Kannada', 'weglot'),
            'kk' => __('Kazakh', 'weglot'),
            'km' => __('Khmer', 'weglot'),
            'ko' => __('Korean', 'weglot'),
            'ku' => __('Kurdish', 'weglot'),
            'ky' => __('Kyrgyz', 'weglot'),
            'lo' => __('Lao', 'weglot'),
            'la' => __('Latin', 'weglot'),
            'lv' => __('Latvian', 'weglot'),
            'lt' => __('Lithuanian', 'weglot'),
            'lb' => __('Luxembourgish', 'weglot'),
            'mk' => __('Macedonian', 'weglot'),
            'mg' => __('Malagasy', 'weglot'),
            'ms' => __('Malay', 'weglot'),
            'ml' => __('Malayalam', 'weglot'),
            'mt' => __('Maltese', 'weglot'),
            'mi' => __('Māori', 'weglot'),
            'mr' => __('Marathi', 'weglot'),
            'mn' => __('Mongolian', 'weglot'),
            'ne' => __('Nepali', 'weglot'),
            'no' => __('Norwegian', 'weglot'),
            'ps' => __('Pashto', 'weglot'),
            'fa' => __('Persian', 'weglot'),
            'pl' => __('Polish', 'weglot'),
            'pt' => __('Portuguese', 'weglot'),
            'pa' => __('Punjabi', 'weglot'),
            'ro' => __('Romanian', 'weglot'),
            'ru' => __('Russian', 'weglot'),
            'sm' => __('Samoan', 'weglot'),
            'gd' => __('Gaelic', 'weglot'),
            'sr' => __('Serbian', 'weglot'),
            'sn' => __('Shona', 'weglot'),
            'sd' => __('Sindhi', 'weglot'),
            'si' => __('Sinhalese', 'weglot'),
            'sk' => __('Slovak', 'weglot'),
            'sl' => __('Slovenian', 'weglot'),
            'so' => __('Somali', 'weglot'),
            'st' => __('Sotho', 'weglot'),
            'es' => __('Spanish', 'weglot'),
            'su' => __('Sundanese', 'weglot'),
            'sw' => __('Swahili', 'weglot'),
            'sv' => __('Swedish', 'weglot'),
            'tl' => __('Tagalog', 'weglot'),
            'ty' => __('Tahitian', 'weglot'),
            'tg' => __('Tajik', 'weglot'),
            'ta' => __('Tamil', 'weglot'),
            'tt' => __('Tatar', 'weglot'),
            'te' => __('Telugu', 'weglot'),
            'th' => __('Thai', 'weglot'),
            'to' => __('Tongan', 'weglot'),
            'tr' => __('Turkish', 'weglot'),
            'uk' => __('Ukrainian', 'weglot'),
            'ur' => __('Urdu', 'weglot'),
            'uz' => __('Uzbek', 'weglot'),
            'vi' => __('Vietnamese', 'weglot'),
            'cy' => __('Welsh', 'weglot'),
            'fy' => __('Frisian', 'weglot'),
            'xh' => __('Xhosa', 'weglot'),
            'yi' => __('Yiddish', 'weglot'),
            'yo' => __('Yoruba', 'weglot'),
            'zu' => __('Zulu', 'weglot'),
        );
    }

    public static function getStrLangByCode($code)
    {
        $langs = self::getStrLangs();
        return (array_key_exists($code, $langs)) ? $langs[$code] : "";
    }
}
